### ISSUE TITLE
Screen power management

### ISSUE THREAD

**Issue by andreabellitto** [linuxmint/cinnamon-settings-daemon#220] opened 2018-02-21 19:30 UTC
```
 * csd version 
3.6.2-1~artful0 amd64
 * Distribution
Ubuntu 17.10
 * Graphics hardware *and* driver used
Intel hd4000 integrated drivers + nvidia gtx860m 390.25
 * 32 or 64 bit
 ```

**Issue**
I'm on Ubuntu 17.10 with Cinnamon 3.6.7, i suffer this bug, i have my screen power management settings as follow:

On battery: turn off screen after 5 minutes of inactivity
On AC: never turn off screen

If turn on my PC while it is attached to AC power source, my screen never turns off on inactivity periods, if then i remove te AC power cable it follow my settings and after 5 minutes of screen inactivity turns off the screen. But if then i attach again my PC to AC power cable, it remains with the 5 minutes timeout setting on the screen power management settings. To make it work again I need to restart my PC or to restart Cinnamon.

It's a very annoyng bug, please investigate on it.

**Steps to reproduce**
1)  set power management settings as follow:

On battery: turn off screen after 5 minutes of inactivity
On AC: never turn off screen

2) Turn on the PC while it is attached to AC power source.
3) remove te AC power cable
4) attach again the PC to AC power cable
5) the PC remains with the 5 minutes timeout setting and does not switch back to the always on setting.

**Expected behaviour**
5a) the PC switch back to the always on setting.

**Comment by xavierhd** [comment] 2018-02-22 04:43
I can reproduce following the same step using Mint 18.3 with Cinnamon 3.6.7.

**Comment by xavierhd** [comment] 2018-02-22 16:09
Also, this seem like it could be related to: ![image](https://user-images.githubusercontent.com/5983431/36548338-0b5f3cf8-17be-11e8-8126-39208ae4e925.png)
When the AC is plugged and at full charge, the battery applet report the time remaining.
From the source code, it seam that it may come from call to `up_client_get_on_battery` function from UPower which would return incorrect state.

**Comment by xavierhd** [comment] 2018-02-23 00:40
https://github.com/linuxmint/cinnamon-settings-daemon/issues/209 is the about the same issue

**Comment by NikoKrause** [comment] 2018-02-23 12:31
I'll close this one, because it's a duplicate of #209

**Closed by NikoKrause** 2018-02-23 12:31 UTC
