### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lexj** [linuxmint/cinnamon-settings-daemon#312] opened 2020-11-23 13:27 UTC
```
 * csd version - 4.6.4+ulyana 
 * Distribution - Mint 20.04
 * AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx Driver - amdgpu,ati 
 * 64 bit
 ```

**Issue**
Crash/lockup

**Steps to reproduce**
I really don't know. I have been having problems with stability on my system, but csd is listed in 2 out of 3 crash reports.

**Expected behaviour**

**Other information**
===================================================================
 Info                                                              
===================================================================
           PID: 1402 (csd-automount)
           UID: 1000 (lexj)
           GID: 1000 (lexj)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-11-23 02:34:23 EST (5h 35min ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (lexj)
       Boot ID: 0836dc2c40204e54b24d41359636a58c
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: ENVY-x360
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.0836dc2c40204e54b24d41359636a58c.1402.1606116863000000000000.lz4
       Message: Process 1402 (csd-automount) of user 1000 dumped core.
                
                Stack trace of thread 1402:
                #0  0x00005642545b5430 n/a (csd-automount + 0x6430)
                #1  0x00007fd01353ca28 n/a (libglib-2.0.so.0 + 0x52a28)
                #2  0x00007fd01353be8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #3  0x00007fd01353c240 n/a (libglib-2.0.so.0 + 0x52240)
                #4  0x00007fd01353c533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #5  0x00007fd013bd137d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #6  0x00005642545b4947 n/a (csd-automount + 0x5947)
                #7  0x00007fd0131e20b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x00005642545b4aae n/a (csd-automount + 0x5aae)
                
                Stack trace of thread 1452:
                #0  0x00007fd0132d0aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fd01353c1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd01353c2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fd01414f99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007fd013565931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd012a18609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd0132dd293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 1448:
                #0  0x00007fd0132d0aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fd01353c1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd01353c2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fd01353c331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007fd013565931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd012a18609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd0132dd293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 1450:
                #0  0x00007fd0132d0aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fd01353c1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd01353c533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007fd013793eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007fd013565931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd012a18609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd0132dd293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1402]
[New LWP 1452]
[New LWP 1448]
[New LWP 1450]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005642545b5430 in ?? ()
[Current thread is 1 (Thread 0x7fd012142a80 (LWP 1402))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1402]
[New LWP 1452]
[New LWP 1448]
[New LWP 1450]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005642545b5430 in ?? ()
[Current thread is 1 (Thread 0x7fd012142a80 (LWP 1402))]
#0  0x00005642545b5430 in ?? ()
#1  0x00007fd01353ca28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fd01353be8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fd01353c240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fd01353c533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd013bd137d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00005642545b4947 in ?? ()
#7  0x00007fd0131e20b3 in __libc_start_main (main=0x5642545b4770, argc=1, argv=0x7ffe1c260988, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe1c260978) at ../csu/libc-start.c:308
#8  0x00005642545b4aae in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1402]
[New LWP 1452]
[New LWP 1448]
[New LWP 1450]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005642545b5430 in ?? ()
[Current thread is 1 (Thread 0x7fd012142a80 (LWP 1402))]

Thread 4 (Thread 0x7fd0113d0700 (LWP 1450)):
#0  0x00007fd0132d0aff in __GI___poll (fds=0x5642546f6160, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd01353c1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd01353c533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd013793eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fd013565931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd012a18609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140531619137280, -5129322333124668431, 140729370674750, 140729370674751, 140729370674896, 140531619134592, 5147859540953289713, 5147853795438515185}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd0132dd293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7fd011bd1700 (LWP 1448)):
#0  0x00007fd0132d0aff in __GI___poll (fds=0x5642546e5520, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd01353c1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd01353c2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd01353c331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fd013565931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd012a18609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140531627529984, -5129322333124668431, 140729370674318, 140729370674319, 140729370674464, 140531627527296, 5147860637780562929, 5147853795438515185}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd0132dd293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7fd010b7a700 (LWP 1452)):
#0  0x00007fd0132d0aff in __GI___poll (fds=0x5642547042b0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd01353c1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd01353c2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd01414f99d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007fd013565931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd012a18609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140531610396416, -5129322333124668431, 140729370673822, 140729370673823, 140729370673968, 140531610393728, 5147858382385861617, 5147853795438515185}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd0132dd293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7fd012142a80 (LWP 1402)):
#0  0x00005642545b5430 in ?? ()
No symbol table info available.
#1  0x00007fd01353ca28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd01353be8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd01353c240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fd01353c533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd013bd137d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x00005642545b4947 in ?? ()
No symbol table info available.
#7  0x00007fd0131e20b3 in __libc_start_main (main=0x5642545b4770, argc=1, argv=0x7ffe1c260988, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe1c260978) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94842883111568, -5129322333124668431, 94842883099264, 140729370675584, 0, 0, 5128690472140690417, 5147854891907961841}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffe1c260988}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#8  0x00005642545b4aae in ?? ()
No symbol table info available.
#0  0x00005642545b5430 in ?? ()
#1  0x00007fd01353ca28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fd01353be8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fd01353c240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fd01353c533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd013bd137d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00005642545b4947 in ?? ()
#7  0x00007fd0131e20b3 in __libc_start_main (main=0x5642545b4770, argc=1, argv=0x7ffe1c260988, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe1c260978) at ../csu/libc-start.c:308
#8  0x00005642545b4aae in ?? ()

**Comment by leigh123linux** [comment] 2020-11-23 14:50
Duplicate of #306

**Closed by leigh123linux** 2020-11-23 14:50 UTC
