### ISSUE TITLE
[Crash Report] csd-keyboard  

### ISSUE THREAD

**Issue by katemakescode** [linuxmint/cinnamon-settings-daemon#308] opened 2020-10-25 18:12 UTC
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**

I've received a crash report at 06:05:33 NZDT this morning (2020-10-26), which I'm guessing is related to the problem I'm having upgrading my drivers.

**Steps to reproduce**

Weirdly, I have no recollection of a crash at that time. I logged on about then, and afterwards had trouble installing security patches. I fixed that using mintupgrade (thanks to the folks on Linux Mint Forums), then found that I couldn't launch the driver manager, at least not from System Reports. It was at this point that I found the crash report.

The only other things I've done this morning are launch Chrome and change my desktop image.

**Expected behaviour**

I expected to be able to launch the driver manager, and, as suggested, install the available driver for NVIDIA Corporation: GP104 [GeForce GTX 1070]. I assume it's an upgrade.

**Other information**

See stack trace posted here: https://termbin.com/3u21

**Comment by leigh123linux** [comment] 2020-10-25 18:31
Duplicate of #279

**Closed by leigh123linux** 2020-10-25 18:31 UTC

**Comment by katemakescode** [comment] 2020-10-25 18:40
[crash.tar.gz](https://github.com/linuxmint/cinnamon-settings-daemon/files/5435645/crash.tar.gz)
[book_tokens.pdf](https://github.com/linuxmint/cinnamon-settings-daemon/files/5435646/book_tokens.pdf)
