### ISSUE TITLE
 PID: 1177 (csd-automount)

### ISSUE THREAD

**Issue by Febrian-Aji-Sasetio** [linuxmint/cinnamon-settings-daemon#303] opened 2020-09-22 23:51 UTC
```
 * csd version
ii  cinnamon-settings-daemon                   4.6.4+ulyana                          amd64        daemon handling the Cinnamon session settings

 * Distribution
Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 

 * Graphics hardware *and* driver used
Device-1: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics 
           vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:22b1 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 400 (BSW) v: 4.6 Mesa 20.0.8 compat-v: 3.0 
           direct render: Yes 

Local Storage: total: 465.76 GiB used: 17.10 GiB (3.7%) 
           ID-1: /dev/sda vendor: Seagate model: ST500LT012-1DG142 size: 465.76 GiB 
           speed: 6.0 Gb/s serial: <filter>

 * 64 bit

 ```

**Issue**
/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount

Info                                                              
===================================================================
           PID: 1177 (csd-automount)
[crash.tar.gz](https://github.com/linuxmint/cinnamon-settings-daemon/files/5264657/crash.tar.gz)

           UID: 1000 (ibn-suparno)
           GID: 1000 (ibn-suparno)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-09-21 21:15:35 WIB (1 day 9h ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (ibn-suparno)
       Boot ID: a382f0b30dc043d18a828480323ff97c
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: Al-Lizaaz
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.a382f0b30dc043d18a828480323ff97c.1177.1600697735000000000000.lz4
       Message: Process 1177 (csd-automount) of user 1000 dumped core.
                
                Stack trace of thread 1177:
                #0  0x0000562dc6a2d430 n/a (csd-automount + 0x6430)
                #1  0x00007f774e98fa28 n/a (libglib-2.0.so.0 + 0x52a28)
                #2  0x00007f774e98ee8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #3  0x00007f774e98f240 n/a (libglib-2.0.so.0 + 0x52240)
                #4  0x00007f774e98f533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #5  0x00007f774f02437d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #6  0x0000562dc6a2c947 n/a (csd-automount + 0x5947)
                #7  0x00007f774e6350b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x0000562dc6a2caae n/a (csd-automount + 0x5aae)
                
                Stack trace of thread 1249:
                #0  0x00007f774e72396f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f774e98f1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f774e98f2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f774c74e99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f774e9b8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f774de6d609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f774e730103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1236:
                #0  0x00007f774e72396f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f774e98f1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f774e98f533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f774ebe6eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f774e9b8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f774de6d609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f774e730103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1228:
                #0  0x00007f774e72396f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f774e98f1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f774e98f2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f774e98f331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f774e9b8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f774de6d609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f774e730103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1177]
[New LWP 1249]
[New LWP 1236]
[New LWP 1228]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562dc6a2d430 in ?? ()
[Current thread is 1 (Thread 0x7f774d597a80 (LWP 1177))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1177]
[New LWP 1249]
[New LWP 1236]
[New LWP 1228]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562dc6a2d430 in ?? ()
[Current thread is 1 (Thread 0x7f774d597a80 (LWP 1177))]
#0  0x0000562dc6a2d430 in ?? ()
#1  0x00007f774e98fa28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f774e98ee8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f774e98f240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f774e98f533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f774f02437d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x0000562dc6a2c947 in ?? ()
#7  0x00007f774e6350b3 in __libc_start_main (main=0x562dc6a2c770, argc=1, argv=0x7ffce9cdaf28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce9cdaf18) at ../csu/libc-start.c:308
#8  0x0000562dc6a2caae in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1177]
[New LWP 1249]
[New LWP 1236]
[New LWP 1228]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562dc6a2d430 in ?? ()
[Current thread is 1 (Thread 0x7f774d597a80 (LWP 1177))]

Thread 4 (Thread 0x7f774cfbc700 (LWP 1228)):
#0  0x00007f774e72396f in ?? () at ../sysdeps/wordsize-64/../../io/fts.c:511 from /lib/x86_64-linux-gnu/libc.so.6
No locals.
#1  0x0000562dc7727510 in ?? ()
No symbol table info available.
#2  0x0000562dc7727510 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0xffffffff00000001 in ?? ()
No symbol table info available.
#5  0x0000562dc7728c70 in ?? ()
No symbol table info available.
#6  0x00007f774e98f1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007f774e98f2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007f774e98f331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007f774e9b8931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007f774de6d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140150369404672, 1143553235982535137, 140724231055918, 140724231055919, 140724231056064, 140150369401984, -1067302067946862111, -1067304362346362399}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#11 0x00007f774e730103 in __init_misc (argc=<optimized out>, argv=0x7f774cfbc700, envp=0xffffffff) at init-misc.c:33
        p = <optimized out>
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (Thread 0x7f7747fff700 (LWP 1236)):
#0  0x00007f774e72396f in ?? () at ../sysdeps/wordsize-64/../../io/fts.c:511 from /lib/x86_64-linux-gnu/libc.so.6
No locals.
#1  0x0000562dc7738110 in ?? ()
No symbol table info available.
#2  0x0000562dc7738110 in ?? ()
No symbol table info available.
#3  0x0000000000000002 in ?? ()
No symbol table info available.
#4  0xffffffff00000001 in ?? ()
No symbol table info available.
#5  0x0000562dc77367b0 in ?? ()
No symbol table info available.
#6  0x00007f774e98f1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007f774e98f533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007f774ebe6eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#9  0x00007f774e9b8931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007f774de6d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140150285793024, 1143553235982535137, 140724231056350, 140724231056351, 140724231056496, 140150285790336, -1067291108800935455, -1067304362346362399}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#11 0x00007f774e730103 in __init_misc (argc=<optimized out>, argv=0x7f7747fff700, envp=0xffffffff) at init-misc.c:33
        p = <optimized out>
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (Thread 0x7f77477fe700 (LWP 1249)):
#0  0x00007f774e72396f in ?? () at ../sysdeps/wordsize-64/../../io/fts.c:511 from /lib/x86_64-linux-gnu/libc.so.6
No locals.
#1  0x0000562dc7745dc0 in ?? ()
No symbol table info available.
#2  0x0000562dc7745dc0 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0xffffffff00000001 in ?? ()
No symbol table info available.
#5  0x0000562dc7745f10 in ?? ()
No symbol table info available.
#6  0x00007f774e98f1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007f774e98f2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007f774c74e99d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#9  0x00007f774e9b8931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007f774de6d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140150277400320, 1143553235982535137, 140724231055422, 140724231055423, 140724231055568, 140150277397632, -1067290008752436767, -1067304362346362399}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#11 0x00007f774e730103 in __init_misc (argc=<optimized out>, argv=0x7f77477fe700, envp=0xffffffff) at init-misc.c:33
        p = <optimized out>
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (Thread 0x7f774d597a80 (LWP 1177)):
#0  0x0000562dc6a2d430 in ?? ()
No symbol table info available.
#1  0x00007f774e98fa28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f774e98ee8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f774e98f240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f774e98f533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f774f02437d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x0000562dc6a2c947 in ?? ()
No symbol table info available.
#7  0x00007f774e6350b3 in __libc_start_main (main=0x562dc6a2c770, argc=1, argv=0x7ffce9cdaf28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce9cdaf18) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94754606086800, 1143553235982535137, 94754606074496, 140724231057184, 0, 0, -1141834026651432479, -1067305431699633695}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffce9cdaf28}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#8  0x0000562dc6a2caae in ?? ()
No symbol table info available.
#0  0x0000562dc6a2d430 in ?? ()
#1  0x00007f774e98fa28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f774e98ee8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f774e98f240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f774e98f533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f774f02437d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x0000562dc6a2c947 in ?? ()
#7  0x00007f774e6350b3 in __libc_start_main (main=0x562dc6a2c770, argc=1, argv=0x7ffce9cdaf28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffce9cdaf18) at ../csu/libc-start.c:308
#8  0x0000562dc6a2caae in ?? ()

Give me solution ya sir.
Thanks for your attention.

**Comment by leigh123linux** [comment] 2020-09-23 02:08
Duplicate of #302

**Closed by leigh123linux** 2020-09-23 02:08 UTC
