### ISSUE TITLE
csd-keyboard crash report

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [linuxmint/cinnamon-settings-daemon#281] opened 2020-01-26 21:47 UTC
```
 * csd version - 4.4.0+tricia 
 * Distribution - Linux Mint Cinnamon 19.3
 * Graphics hardware *and* driver used : AMD Radeon HD 8750M - Mesa 19.3.2 (kisak-mesa ppa)
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Cinnamon randomly crashes, and after opening System Reports, I found multiple system crash reports, and I decided to upload them. There are 2 crash reports related to csd-keyboard

[Pasetbin1.txt](https://github.com/linuxmint/cinnamon-settings-daemon/files/4114491/Pasetbin1.txt)

[Pasetbin2.txt](https://github.com/linuxmint/cinnamon-settings-daemon/files/4114492/Pasetbin2.txt)

**Comment by leigh123linux** [comment] 2020-01-26 22:30
Closed, duplicate of #279

**Closed by leigh123linux** 2020-01-26 22:30 UTC
